apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: NodePort
  selector:
    app: stockmarket-q5
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8085
      nodePort: 30007
